### ISSUE TITLE
Downloadable Resume

### ISSUE THREAD

**Issue by kimjev-webdev** [kimjev-webdev/kimjevonportfolio#2]
**User Story**

As a recruiter, I want to find a resume and a list of the artist's technical skills on the portfolio site so that I can evaluate their qualifications for relevant job openings.

Acceptance Criteria: 

- [ ] A downloadable resume and a skills section detailing employment history, education and bio. (Supplementary information which isn’t crucial to all users of the site but is accessible for those who want to view it).
- [ ] 
- [ ] Resume should be concise and well formatted as the website itself should do most of the talking. 

**Tasks**

- [ ] Create up to date C.V
- [ ] Format CV to compliment website styling 
- [ ] Download CV button at bottom of bio on website.
